Make most imports explicit
FreeProving/haskell-src-transformations pull request #20
Opened 2020-06-19 11:56 UTC by stu204146-kiel

Most exports are explicit now

2020-06-19 19:53 UTC, just95 requested changes

2020-06-19 19:53 UTC, just95 commented on src/exe/Main.hs
>      -- ^ Flag that indicates whether to enable trivial case completion or not.
This comment somehow got moved.

2020-06-19 19:53 UTC, just95 commented on src/lib/GuardElimination.hs
>  import           Control.Monad
This import is missing the explicit import list.

2020-06-19 19:53 UTC, just95 commented on src/test/AlgoTests.hs
>  import           Test.Hspec
This import is also missing explicit imports.

2020-06-19 21:57 UTC, stu204767 requested changes

2020-06-19 21:57 UTC, stu204767 commented on src/lib/Algo.hs
> +  -> HSE.Exp ()        -- ^ The error expression for pattern-matching failures.
These too.

2020-06-19 21:57 UTC, stu204767 commented on src/lib/Algo.hs
> +  -> HSE.Exp ()   -- ^ The error expression for pattern-matching failures.
These comments should be aligned.

2020-06-19 21:57 UTC, stu204767 commented on src/lib/Algo.hs
>    -> [[Eqs]]  -- ^ Groups of equations (see 'groupPat').
This one too.
```suggestion
  -> [[Eqs]]      -- ^ Groups of equations (see 'groupPat').
```

2020-06-19 21:57 UTC, stu204767 commented on src/lib/Algo.hs
>    -> [Eqs]    -- ^ The equations.
This one as well.
```suggestion
  -> [Eqs]        -- ^ The equations.
```

2020-06-19 21:57 UTC, stu204767 commented on src/lib/Algo.hs
>    -> [Eqs]    -- ^ The equations to generate alternatives for.
```suggestion
  -> [Eqs]        -- ^ The equations to generate alternatives for.
```

2020-06-19 21:57 UTC, stu204767 commented on src/lib/Algo.hs
>    -> [Eqs]    -- ^ A group of equations (see 'groupByCons').
```suggestion
  -> [Eqs]        -- ^ A group of equations (see 'groupByCons').
```

2020-06-19 21:57 UTC, stu204767 commented on src/lib/GuardElimination.hs
>                              -- free Variable for the error case
These comments should be aligned as well.

2020-06-19 21:57 UTC, stu204767 commented on src/lib/Algo.hs
>  import           Data.Function
Shouldn't these be explicit as well?
```suggestion
import           Data.List                      ( partition
                                                , groupBy
                                                )
import           Data.Function                  ( on )
```

2020-06-19 21:57 UTC, stu204767 commented on src/lib/GuardElimination.hs
> +  -> PM ([HSE.Decl ()], HSE.Pat ()) -- var bindings , variable for next match
These too.

2020-06-22 12:45 UTC, just95 approved these changes

2020-06-22 13:28 UTC, stu204767 approved these changes

2020-06-22 17:01 UTC, merged