Integrate GHC-lib into `Main` module and unit tests
FreeProving/haskell-src-transformations pull request #43
Opened 2020-07-28 15:59 UTC by just95

### Issue

Closes #33.

### Description of the Change

Type classes [`Parseable`](https://github.com/FreeProving/haskell-src-transformations/blob/703ab361d59f81ad347153b2ce30e10c3e323f58/src/lib/HST/Frontend/Parser.hs#L46), [`Transformable`](https://github.com/FreeProving/haskell-src-transformations/blob/703ab361d59f81ad347153b2ce30e10c3e323f58/src/lib/HST/Frontend/Transformer.hs#L32) and [`PrettyPrintable`](https://github.com/FreeProving/haskell-src-transformations/blob/703ab361d59f81ad347153b2ce30e10c3e323f58/src/lib/HST/Frontend/PrettyPrinter.hs#L22) have been added. The type classes are parameterized over the same type argument that is used for the intermediate syntax (i.e., [`HSE`](https://github.com/FreeProving/haskell-src-transformations/blob/703ab361d59f81ad347153b2ce30e10c3e323f58/src/lib/HST/Frontend/FromHSE.hs#L24) and [`GHC`](https://github.com/FreeProving/haskell-src-transformations/blob/703ab361d59f81ad347153b2ce30e10c3e323f58/src/lib/HST/Frontend/FromGHC.hs#L46)). The type classes provide operations for parsing, transforming (to and drom the intermediate syntax) and pretty printing Haskell modules.

An effect has been added that provides the same operations as the type classes. The purpose of the effect is to make it easier to switch the front end at runtime. There are two handlers. One for running a computation with a specific front end and one for running a computation with all front ends that are listed in the [`frontendMap`](https://github.com/FreeProving/haskell-src-transformations/blob/703ab361d59f81ad347153b2ce30e10c3e323f58/src/lib/HST/Options.hs#L48). The former handler is used in the `Main` module and the latter in the test cases.

Currently, the `ApplicationTests` module is the only test that uses both front ends. Testing `CoreAlgorithmTests` with both front ends would have required additional operations for the type classes and effects since patterns are parsed instead of modules. However, I don't think that this is a problem. The results of the `CoreAlgorithm` should not depend on the front end. 

### Alternate Designs

An implementation without the effect would be possible, too. However, the effect handlers help to hide some complexity associated with switching the type class instances such as helper functions and `TypeApplications`.

### Verification Process

The `Main` module was tested with the queue examples from the `./example` directory. The unit tests still pass. I've made sure that both front ends are tested by deliberately inserting bugs into the `FromGHC` and `FromHSE` modules and running the `./tool/test.sh` script.

### Additional Notes

In order to implement the [`runWithAllFrontends`](https://github.com/FreeProving/haskell-src-transformations/blob/703ab361d59f81ad347153b2ce30e10c3e323f58/src/lib/HST/Effect/WithFrontend.hs#L131) handler, I had to use higher rank polymorphism (i.e., `RankNTypes`) because the [`WithFrontend`](https://github.com/FreeProving/haskell-src-transformations/blob/703ab361d59f81ad347153b2ce30e10c3e323f58/src/lib/HST/Effect/WithFrontend.hs#L55) has a type argument for the front end. In consequence, the [`runEnv`](https://github.com/FreeProving/haskell-src-transformations/blob/703ab361d59f81ad347153b2ce30e10c3e323f58/src/lib/HST/Effect/Env.hs#L63) handler must always be invoked within the computation that is handled by `runWithAllFrontends` since the [`Env`](https://github.com/FreeProving/haskell-src-transformations/blob/703ab361d59f81ad347153b2ce30e10c3e323f58/src/lib/HST/Effect/Env.hs#L39) effect also has such a type argument. This also makes sense from a semantic viewpoint: each front end should be tested with its own environment and fresh variables.

2020-07-29 21:31 UTC, stu204767 requested changes

2020-07-29 21:31 UTC, stu204767 commented on src/lib/HST/Effect/Report.hs
> +-- | Handels the 'Cancel' effect by reporting the given fatal error message
```suggestion
-- | Handles the 'Cancel' effect by reporting the given fatal error message
```

2020-07-29 21:31 UTC, stu204767 commented on src/lib/HST/Effect/WithFrontend.hs
> +--   instead of the module that define the type classes.
```suggestion
--   instead of the modules that define the type classes.
```

2020-07-29 21:31 UTC, stu204767 commented on src/lib/HST/Effect/WithFrontend.hs
> +-- | An effect for computation that need to use different front ends for
```suggestion
-- | An effect for computations that need to use different front ends for
```

2020-07-29 21:31 UTC, stu204767 commented on src/lib/HST/Effect/WithFrontend.hs
> +    -> S.Module f    -- ^ The module to transform back.
Preparation for Floskell:
```suggestion
    ::ParsedModule f -- ^ The original input module.
    -> S.Module f     -- ^ The module to transform back.
```

2020-07-29 21:31 UTC, stu204767 commented on src/lib/HST/Frontend/FromGHC.hs
>    ]
Did you remove the `FunCon` for a specific reason? If so, should it be removed everywhere else as well?

2020-07-29 21:31 UTC, stu204767 commented on src/lib/HST/Frontend/Parser.hs
> +-- | Parses a Haskell module with the parser from @haskell-src-exts@.
I think "of" fits better here.
```suggestion
-- | Parses a Haskell module with the parser of @haskell-src-exts@.
```

2020-07-29 21:31 UTC, stu204767 commented on src/lib/HST/Frontend/Parser.hs
> +          ++ show (HSE.srcLine srcLoc)
I suppose this should be the column:
```suggestion
          ++ show (HSE.srcColumn srcLoc)
```

2020-07-29 21:31 UTC, stu204767 commented on src/lib/HST/Frontend/Parser.hs
> +-- | Parses a Haskell module with the parser from @ghc-lib@.
```suggestion
-- | Parses a Haskell module with the parser of @ghc-lib-parser@.
```

2020-07-29 21:31 UTC, stu204767 commented on src/lib/HST/Frontend/Parser.hs
> +    -- | Reports a error message or warning from @ghc-lib@.
```suggestion
    -- | Reports an error message or warning from @ghc-lib-parser@.
```

2020-07-29 21:31 UTC, stu204767 commented on src/lib/HST/Frontend/PrettyPrinter.hs
> +                   , HSE.ribbonsPerLine = 1.5
Do we want to keep this style or change it to something else (for example `80` and `1.0`, which should be what we currently use for our own source code)?

2020-07-29 21:31 UTC, stu204767 commented on src/lib/HST/Frontend/PrettyPrinter.hs
> +--   @ghc-lib@.
```suggestion
--   @ghc-lib-parser@.
```

2020-07-29 21:31 UTC, stu204767 commented on src/lib/HST/Frontend/Parser.hs
> +    = ParsedModuleHSE { unParsedModuleHSE :: HSE.Module HSE.SrcSpanInfo }
Why is the module called `unParsedModule`?

2020-07-29 21:31 UTC, stu204767 commented on src/lib/HST/Frontend/Transformer.hs
> +--   can be transformed to and from the the intermediate syntax.
```suggestion
--   can be transformed to and from the intermediate syntax.
```

2020-07-29 21:31 UTC, stu204767 commented on src/test/HST/ApplicationTests.hs
> +--   strings are equal modulo whitespace.
```suggestion
-- | Pretty prints both given modules and tests whether the resulting strings
--   are equal modulo whitespace.
```

2020-07-29 21:31 UTC, stu204767 commented on src/test/HST/ApplicationTests.hs
> +          , "lengthL(_:xs) = 1 + lengthL xs"
```suggestion
          , "lengthL (_:xs) = 1 + lengthL xs"
```

2020-07-30 06:45 UTC, just95 commented on src/lib/HST/Frontend/FromGHC.hs
>    ]
There is no data constructor for functions. Since we don't need type constructors, we could remove `FunCon` from the AST.

2020-07-30 07:03 UTC, just95 commented on src/lib/HST/Frontend/Parser.hs
> +    = ParsedModuleHSE { unParsedModuleHSE :: HSE.Module HSE.SrcSpanInfo }
It's quite common to call the destructor of the `Constructor` of a `newtype` wrapper `unConstructor`. But we can also call it `unwrapParsedModuleHSE` or `getParsedModuleHSE` if that sounds better to you.

2020-07-30 07:15 UTC, just95 commented on src/lib/HST/Frontend/Parser.hs
> +          ++ show (HSE.srcLine srcLoc)
Good catch!

2020-07-30 07:20 UTC, just95 commented on src/lib/HST/Frontend/PrettyPrinter.hs
> +                   , HSE.ribbonsPerLine = 1.5
Sounds plausible, I'll change it. In the long term we should consider to use [`exactPrint`](https://hackage.haskell.org/package/haskell-src-exts-1.23.1/docs/Language-Haskell-Exts-ExactPrint.html#v:exactPrint) in order to preserve comments and whitespace but that's blocked by #34.

```suggestion
                   , HSE.lineLength     = 80
                   , HSE.ribbonsPerLine = 1.0
```

2020-07-30 07:35 UTC, just95 commented on src/lib/HST/Effect/WithFrontend.hs
> +    -> S.Module f    -- ^ The module to transform back.
Unlike Brittany, Floskell does not move the `::` into the next line but would format the code as follows.

```haskell
data WithFrontend f m a where
    ParseModule :: FilePath -- ^ The name of the input file.
        -> String           -- ^ The contents of the input file.
        -> WithFrontend f m (ParsedModule f)
```

Thus, the comments will have to be aligned manually anyway.

2020-07-30 08:13 UTC, stu204767 commented on src/lib/HST/Frontend/Parser.hs
> +    = ParsedModuleHSE { unParsedModuleHSE :: HSE.Module HSE.SrcSpanInfo }
I'm for `getParsedModuleHSE` (and `getParsedModuleGHC` of course).

2020-07-30 09:04 UTC, just95 commented on src/lib/HST/Frontend/Parser.hs
> +    = ParsedModuleHSE { unParsedModuleHSE :: HSE.Module HSE.SrcSpanInfo }
See 0403cc343e93b9c9d353f034509eb80f4c613ace.

2020-07-30 10:28 UTC, just95 commented on src/lib/HST/Frontend/FromGHC.hs
>    ]
If now removed `FunCon` in 72b6008a7df2506b9cafb0c47585239c4f3e7626. I've also renamed `S.ListCon` to `S.NilCon` to make clearer that it is the name of a data constructor.

2020-07-31 10:08 UTC, stu204767 requested changes

2020-07-31 10:08 UTC, stu204767 commented on src/test/HST/ApplicationTests.hs
> +      , "lengthL(_:xs) = 1 + lengthL xs"
```suggestion
      , "lengthL (_:xs) = 1 + lengthL xs"
```

2020-07-31 10:08 UTC, stu204767 commented on src/test/HST/ApplicationTests.hs
> +                      ["module A where", "f :: a -> a", "f x = x"]
With the new function `shouldTransformTo`, we can remove the now superfluous `do`s here and in the other test cases.

2020-07-31 10:08 UTC, stu204767 commented on src/lib/HST/Frontend/GHC/From.hs
> +        $ (  "Wired in data constructor not supported: "
```suggestion
        $ (  "Wired-in data constructor not supported: "
```

2020-07-31 12:16 UTC, stu204767 approved these changes

2020-07-31 13:50 UTC, merged