Issue 34
FreeProving/haskell-src-transformations pull request #46
Opened 2020-08-25 11:51 UTC by stu204146-kiel

### Issue

The SrcSpans are preserved as much as possible for better error messages.

### Description of the Change
I have changed the code of the features such that the source-span information is preserved during the features.

### Verification Process

I tried to test several programs over which i ran the compiler.

### Additional Notes
Maybe guard elemination contains some bugs.
I have added a SrcSpan-attribute to ``GExp''.

2020-08-26 13:34 UTC, stu204767 requested changes
There are some more `S.NoSrcSpan`s left that probably can be easily avoided.
Also, you apparently haven't yet looked at some of the other modules containing unnecessary `S.NoSrcSpan`s, especially `HST.Feature.Optimization`.

2020-08-26 13:34 UTC, stu204767 commented on src/lib/HST/Application.hs
> +    $ S.Match S.NoSrcSpan name nVars (S.UnGuardedRhs rhsSpan nExp') Nothing
I think the source span of the corresponding `FunBind` should be used here, both for the `Match` and the `UnGuardedRhs`. This `rhsSpan` seems to belong to the first match of the original function only, while we want to span all matches.

2020-08-26 13:34 UTC, stu204767 commented on src/lib/HST/CoreAlgorithm.hs
> +               nvars
If I backtracked the code correctly, then this `S.Pat` is (always?) generated in the `freshVarPat` function in the `HST.Effect.Fresh` module, where it gets `S.NoSrcSpan` as its source span.
While I do think that there is no perfect source span for a generated case alternative, there probably exists a better solution, possibly using the equations (`Eqs`) that occur in most other functions of this module.

2020-08-26 13:34 UTC, stu204767 commented on src/lib/HST/CoreAlgorithm.hs
> +    decomposeConPat (S.PInfixApp nspan n listCon (S.PList S.NoSrcSpan nv))
I think we should use the source span of the entire list and not the one for the first element here. We don't have a good source span for the remaining list, so we should use the source span of the entire list again in my opinion.
```suggestion
    decomposeConPat (S.PInfixApp s n listCon (S.PList s nv))
```

2020-08-26 13:34 UTC, stu204767 commented on src/lib/HST/Feature/CaseCompletion.hs
> +completeLambda s ps e insideLet = do
Nice, adding an additional parameter like in this case would help removing some of the remaining `NoSrcSpan`s too.

2020-08-26 13:34 UTC, stu204767 commented on src/lib/HST/Feature/GuardElimination.hs
> +                   }
Nice.

2020-08-26 13:34 UTC, stu204767 commented on src/lib/HST/Feature/GuardElimination.hs
> +    $ S.Match lhsSpan name varPats (S.UnGuardedRhs S.NoSrcSpan expr') Nothing
Just as in the `useAlgo` function in the `Application` module, you could pass the source span of the `FunBind` to this function and use it here for the `Match` and the `UnGuardedRhs`.

2020-08-28 13:24 UTC, just95 requested changes

2020-08-28 13:24 UTC, just95 commented on src/lib/HST/Effect/Fresh.hs
>  freshName prefix = S.Ident S.NoSrcSpan <$> freshIdent prefix
You could express the old functions in terms of their new `*WithSpan` variations.

```suggestion
freshName = flip freshNameWithSpan S.NoSrcSpan
```

I would also consider to call them `*WithSrcSpan` for consistency.

2020-08-28 13:24 UTC, just95 commented on src/lib/HST/Feature/Optimization.hs
> +          -> S.SrcSpan a
Add documentation to these parameters to make clear which source span is which.

2020-09-07 12:42 UTC, just95 approved these changes

2020-09-08 17:10 UTC, stu204767 requested changes
There are still three suggestions left from my last review. Have you looked at them?

2020-09-08 17:10 UTC, stu204767 commented on src/lib/HST/Effect/Fresh.hs
> +--   value.
```suggestion
-- | Generates a name for a fresh variable and sets the 'S.SrcSpan' to the
--   given value.
```

2020-09-08 17:10 UTC, stu204767 commented on src/lib/HST/Effect/Fresh.hs
> +--   to the given value.
```suggestion
-- | Generates an unqualified name for a fresh variable and sets the
--   'S.SrcSpan' to the given value.
```

2020-09-08 17:10 UTC, stu204767 commented on src/lib/HST/Effect/Fresh.hs
> +--   value.
```suggestion
-- | Generates a fresh variable expression and sets the 'S.SrcSpan' to the
--   given value.
```

2020-09-08 17:10 UTC, stu204767 commented on src/lib/HST/Effect/Fresh.hs
> +-- | Generates a fresh variable pattern which `S.SrcSpan` is identical to the
```suggestion
-- | Generates a fresh variable pattern whose 'S.SrcSpan' is identical to the
```

2020-09-08 17:10 UTC, stu204767 commented on src/lib/HST/Feature/Optimization.hs
> +          -> S.SrcSpan a  -- ^ The source span for the matched expression
```suggestion
          => S.SrcSpan a  -- ^ The source span for the whole case expression.
          -> S.SrcSpan a  -- ^ The source span for the matched expression.
```

2020-09-21 08:20 UTC, stu204767 requested changes
Okay, this seems to address one of the remaining suggestions I had, but what about [this one](https://github.com/FreeProving/haskell-src-transformations/pull/46#discussion_r477304108)?
Otherwise, you still have to merge the `main` branch into this one.

2020-09-21 08:20 UTC, stu204767 commented on src/lib/HST/Application.hs
> +      srcSpans = (map S.getSrcSpan) . S.matchPats . head $ ms
Shouldn't these parantheses be redundant?
```suggestion
      srcSpans = map S.getSrcSpan . S.matchPats . head $ ms
```

2020-09-22 11:28 UTC, stu204767 approved these changes

2020-09-22 15:55 UTC, merged