Remove bug for simple case expressions #50
FreeProving/haskell-src-transformations pull request #54
Opened 2020-09-04 09:30 UTC by stu204146-kiel

### Issue

Closes #50 

### Description of the Change
I have changed the case completion such that simple case expressions are matched correctly.

### Verification Process
I have tested it with the module given in the issue and the basic unit tests already given.

2020-09-07 15:09 UTC, just95 requested changes

2020-09-07 15:09 UTC, just95 commented on src/lib/HST/Feature/CaseCompletion.hs
> +    return $ S.Case S.NoSrcSpan expr [a]
I'm not sure why Floskell formats the code like this, but we could use `MultiWayIf`s to make this more readable.

```suggestion
  if | insideLet -> return $ S.Case S.NoSrcSpan expr [S.alt v res]
     | isCase res -> let S.Case _ _ resAs = res
                     in return $ S.Case S.NoSrcSpan expr resAs
     | otherwise -> return ce
```

However, I'm not entirely sure whether this code is correct in general.

 - In no case the case completion algorithm is applied to the scrutinee. This is probably a bug and could be fixed by adding the following statement.

   ```haskell
   expr' <- completeCase insideLet expr
   ```

 - In the `otherwise` case, the original `case`-expression is returned. Shouldn't case completion be performed at least recusively? `res` cannot be returned directly because it may contain `v`. In order to bind `v`, a `case` expression would have to be inserted like in the `insideLet` case.

   ```haskell
   return $ S.Case S.NoSrcSpan expr [S.alt v res]
   ```

 - Why is it safe to discard the scrutinee if `res` is a `case`-expression?
   My guess is that the scutinee is (assumed to be) always `v` and thus, the alternatives of the `case` expression can be inlined.

 - Why do `let` expressions have to be handled differently? If the above is true, why can't this optimization be applied inside `let`-expressions? According to the [Haskell 2010 Language Report (p. 33, Figure 3.2j)](https://www.haskell.org/definition/haskell2010.pdf) the following identity holds.

   ```haskell
   case v of { x -> e } = (\x -> e) v
   ```

   Thus, we should be able to substitute `v` directly (if `v` occurs only once in `res`).

   ```haskell
   return $ applySubst (singleSubst v expr') res
   ```

   Which would cover the case that `res` is a `case`-expression automatically.

2020-09-10 17:49 UTC, stu204767 requested changes
I can't add much to what @just95 said. I think you should apply the suggestions and ideas he has given and check if the unit tests still work. After that, you could add some more tests explicitely for these changes (for all the sensible suggestions, they should fail before applying the suggestions and succeed after).

2020-09-29 17:24 UTC, stu204767 requested changes

2020-09-29 17:24 UTC, stu204767 commented on src/test/HST/ApplicationTests.hs
> +        in m `shouldTransformTo` expected ---}
All comments here and the entire following test case (that was the replacement test) should be removed.

2020-09-30 13:28 UTC, stu204767 requested changes
You removed the wrong test. The test containing a `let` expression was the replacement that should be removed, not the one that was commented out (it was commented out because it caused the bug that has been fixed in this pull request).

2020-09-30 14:08 UTC, stu204767 approved these changes

2020-09-30 15:11 UTC, just95 approved these changes

2020-09-30 15:18 UTC, merged