Fix typos and grammatical errors in README.md
FreeProving/haskell-src-transformations pull request #9
Opened 2020-05-27 10:40 UTC by MajaRet

Changes made:
- use 'an' alpha version instead of 'a alpha version'
- add an apostrophe to 'Wadler's algorithm'
- hyphenate 'left-hand side'
- use 'right-hand sides' instead of 'right sides'
- change 'Haskell-report' to 'Haskell report'
- change 'case-expression' to 'case expressions'

2020-05-28 06:23 UTC, ichistmeinname requested changes

2020-05-28 06:23 UTC, ichistmeinname commented on README.md
> + - It translates pattern matching on left-hand sides into explicit pattern matching on right-hand sides using Wadler's Algorithm for compiling pattern matching.
Is it _Wadler's Algorithm_ or rather only _Wadler's algorithm_? : )

2020-05-28 06:23 UTC, ichistmeinname commented on README.md
> +    Additionally, it contains some special examples that were used to test the [Free Compiler](free-compiler).
Leading whitespace?

2020-05-29 06:38 UTC, ichistmeinname approved these changes

2020-05-29 07:18 UTC, MarvinLira approved these changes

2020-05-29 07:32 UTC, just95 approved these changes

2020-05-29 07:36 UTC, merged